brew "ffmpeg"
brew "gh"
brew "gnupg"
brew "jq"
brew "neofetch"
brew "node"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "redis"
brew "titlecase"
brew "trash"
brew "tree"
brew "yarn"
brew "zsh"
