brew "deno"
brew "exiftool"
brew "ffmpeg"
brew "gh"
brew "git-delta"
brew "git"
brew "gnupg"
brew "imagemagick"
brew "jq"
brew "neofetch"
brew "node@24", link: true
brew "pinentry-mac"
brew "postgresql@18", restart_service: true
brew "redis"
brew "rust"
brew "titlecase"
brew "tree"
brew "uv"
brew "wget"
brew "yt-dlp"
brew "zsh"
